name: Todo Tree Action Test

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  todo-tree-action:
    name: Todo Tree Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Run Todo Tree Action
        uses: alexandretrotel/todo-tree-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changed-only: true
          show-annotations: true
          post-comment: true
          comment-header: "## TODO Report"
